### ISSUE TITLE
лаб 2.

### ISSUE THREAD

**Issue by lasbio** [tenitskayav/BDlab#1]
1. Не выполнен пункт 1 задания ("сохранить в корне проекта") и пункт 5 ("Внесите файл создания базы данных в gitignore")
2. задание 10 - в задании нет требования сортировки, т.е. надо отобрать первых 10 членов клуба. А у вас отобраны первые 10 по алфавиту.
3. задание 11 - кроме членов отобран гость.

**Comment by lasbio** [comment]
1. Не выполнен пункт  5 ("Внесите файл создания базы данных в gitignore")
2. Задание 10 - у вас отсортировано, потом отобрано 10. В задании сначала отобрать, потом отсортировать.

**Comment by tenitskayav** [comment]
Здравствуйте, исправлены ошибки во 2 лабораторной работе
