### ISSUE TITLE
Лаб 3

### ISSUE THREAD

**Issue by lasbio** [tenitskayav/BDlab#2]
1. Задания 2-7 не выполнены

**Comment by tenitskayav** [comment]
задания 2-7 добавлены

**Comment by lasbio** [comment]
2 - не верно. Зачем IF в отборе?  По условиям задачи надо отобрать любые теннисные корты, т.е. в условиях задачи нет facid IN (0,1).  LIKE с полями типа timestamp не применяют.
4 - не верно. У Вас в списке не будет членов без рекомендации.
5 - не верно. В задаче нет условий "только члены" и facid IN (0,1).  
7 - не верно.

**Comment by tenitskayav** [comment]
Все задания исправлены
